defaults:
    - BACKGROUND_TRANSFORM/back
    - BACKGROUND_MASK_TRANSFORM/cutout_mask

JOBS: 8
AUGS_PER_SCENE: 1 #5 # Кол-во новых сцен для каждой сцены
VAL_PART: 0
SPLIT_SEED: 42 # для train/val

ORIG_SET: "/mnt/hdd_2/skopin-s/SergeyS_pet/utils/Background_augmentation/input" # Path to dirs for aug
BACKGROUNDS: "/mnt/hdd_2/skopin-s/SergeyS_pet/utils/Background_augmentation/bg" # "../../backgrounds/" # изображения с фонами
FOREGROUND_SETS: []

NEW_SET: "/mnt/hdd_2/skopin-s/SergeyS_pet/utils/Background_augmentation/outputs/part" # Куда сохранить
